### ISSUE TITLE
Doesn't work on Flarum 0.1.0-beta.12?

### ISSUE THREAD

**Issue by johnvanhulsen** [FriendsOfFlarum/frontpage#6] opened 2020-05-05 19:22 UTC
Hello,

After upgrading from beta 11 to beta 12 I've got the following error:

`Flarum encountered a boot error (ReflectionException)
Class FoF\FrontPage\Listeners\SaveFrontToDatabase does not exist
thrown in vendor/illuminate/container/Container.php on line 779`

Is it possible to use it with beta 12?

**Comment by dsevillamartin** [comment] 2020-05-05 22:48
Issue is that you are using a case-sensitive filesystem. Error is at https://github.com/FriendsOfFlarum/frontpage/blob/d8a24b203551dc3476e730f534157c7e27ca1877/src/Listeners/SaveFrontToDatabase.php#L12 it should be `FoF\`

**Comment by luceos** [comment] 2020-05-07 10:09
> Issue is that you are using a case-sensitive filesystem.

Almost every server runs linux 😊 The issue is that the developer didn't run one ;)

I changed it in master. @johnvanhulsen feel free to try dev-master:

```
composer require fof/frontpage dev-master
```

If that works we can push a new version out.

**Comment by johnvanhulsen** [comment] 2020-05-07 10:19
Yes. dev-master will works! 👏🏻

**Comment by Ralkage** [comment] 2020-07-16 03:33
> 
> 
> > Issue is that you are using a case-sensitive filesystem.
> 
> Almost every server runs linux 😊 The issue is that the developer didn't run one ;)
> 
> I changed it in master. @johnvanhulsen feel free to try dev-master:
> 
> ```
> composer require fof/frontpage dev-master
> ```
> 
> If that works we can push a new version out.

Caught me 😉 pro Windows user right here, but it looks like Microsoft [added case-sensitivity per file and or folder](https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/) as an option back in 2018 so my dev setup has been tweaked since I've learned from this lesson 👏

@johnvanhulsen we'll push this fix along with some others in a patch release soon :)

**Comment by clarkwinkelmann** [comment] 2020-10-06 20:31
The fix has been (finally) released as 0.1.4

**Closed as completed by clarkwinkelmann** 2020-10-06 20:31 UTC
